version: "3.8"

services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # bind mount file cấu hình Nginx
    ports:
      - "80:80" # mapping port 80 của máy host với port 80 của container
    depends_on:
      - nextjs-app
