export const categories = [
  {
    id: 100629,
    name: "Food & Beverages",
    display_name: "Thực phẩm và đồ uống",
    parent_id: 0,
    has_active_children: true,
    has_children: true,
    children: [
      {
        id: 100645,
        name: "Convenience / Ready-to-eat",
        display_name: "Đồ chế biến sẵn",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100780,
            name: "Cooked Food",
            display_name: "Đồ ăn chế biến sẵn",
            parent_id: 100645,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100781,
            name: "Others",
            display_name: "Khác",
            parent_id: 100645,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100782,
            name: "Instant Rice & Porridge",
            display_name: "Cơm và cháo ăn liền",
            parent_id: 100645,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100783,
            name: "Instant Hotpot",
            display_name: "Lẩu ăn liền",
            parent_id: 100645,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100784,
            name: "Instant Noodles",
            display_name: "Mì ăn liền",
            parent_id: 100645,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100646,
        name: "Snacks",
        display_name: "Đồ ăn vặt",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100785,
            name: "Sweets & Candy",
            display_name: "Kẹo",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100786,
            name: "Chocolate",
            display_name: "Sô cô la",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100787,
            name: "Biscuits, Cookies & Wafers",
            display_name: "Bánh quy",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100788,
            name: "Chips & Crisps",
            display_name: "Khoai tây lát",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100789,
            name: "Seeds",
            display_name: "Các loại hạt sấy khô",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100790,
            name: "Popcorn",
            display_name: "Bỏng ngô",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100791,
            name: "Seaweed",
            display_name: "Các loại rong biển ăn liền",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100792,
            name: "Nuts",
            display_name: "Các loại đậu sấy khô",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100793,
            name: "Others",
            display_name: "Khác",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100794,
            name: "Pudding, Jellies & Marshmallow",
            display_name: "Pudding, thạch & kẹo dẻo",
            parent_id: 100646,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100795,
            name: "Dried Snacks",
            display_name: "Thức ăn khô",
            parent_id: 100646,
            has_active_children: true,
            has_children: true,
            children: [],

            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100647,
        name: "Food Staples",
        display_name: "Nhu yếu phẩm",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100796,
            name: "Dried Goods",
            display_name: "Thực phẩm khô",
            parent_id: 100647,
            has_active_children: true,
            has_children: true,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100797,
            name: "Noodles",
            display_name: "Mì",
            parent_id: 100647,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100798,
            name: "Rice",
            display_name: "Gạo",
            parent_id: 100647,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100799,
            name: "Pasta",
            display_name: "Mì Ý",
            parent_id: 100647,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100800,
            name: "Others",
            display_name: "Khác",
            parent_id: 100647,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100801,
            name: "Canned Food",
            display_name: "Thực phẩm đóng hộp",
            parent_id: 100647,
            has_active_children: true,
            has_children: true,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100802,
            name: "Preserved Vegetables",
            display_name: "Rau củ ngâm",
            parent_id: 100647,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100648,
        name: "Cooking Essentials",
        display_name: "Nguyên liệu nấu ăn",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100803,
            name: "Oil",
            display_name: "Dầu ăn",
            parent_id: 100648,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100804,
            name: "Seasonings & Condiments",
            display_name: "Gia vị & Hương liệu",
            parent_id: 100648,
            has_active_children: true,
            has_children: true,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100805,
            name: "Sugar",
            display_name: "Đường",
            parent_id: 100648,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100806,
            name: "Sweetener",
            display_name: "Chất tạo ngọt",
            parent_id: 100648,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100807,
            name: "Stock, Gravy & Instant Soup",
            display_name: "Sốt & súp ăn liền",
            parent_id: 100648,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100808,
            name: "Cooking Paste & Kit",
            display_name: "Gói/ bột gia vị",
            parent_id: 100648,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100809,
            name: "Flavour Enhancers",
            display_name: "Phụ gia thực phẩm",
            parent_id: 100648,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100810,
            name: "Flour Coating",
            display_name: "Bột phủ",
            parent_id: 100648,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100811,
            name: "Others",
            display_name: "Khác",
            parent_id: 100648,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100649,
        name: "Baking Needs",
        display_name: "Đồ làm bánh",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100812,
            name: "Baking Flavoring",
            display_name: "Hương liệu",
            parent_id: 100649,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100813,
            name: "Baking Powder & Soda",
            display_name: "Bột nở và muối nở",
            parent_id: 100649,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100814,
            name: "Baking Premix Flour",
            display_name: "Bột pha sẵn",
            parent_id: 100649,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100815,
            name: "Flour",
            display_name: "Bột mì",
            parent_id: 100649,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100816,
            name: "Food Coloring",
            display_name: "Chất tạo màu",
            parent_id: 100649,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100817,
            name: "Baking Decoration",
            display_name: "Đồ trang trí",
            parent_id: 100649,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100818,
            name: "Others",
            display_name: "Khác",
            parent_id: 100649,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100650,
        name: "Breakfast Cereals & Spread",
        display_name: "Ngũ cốc & mứt",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100819,
            name: "Honey & Maple Syrups",
            display_name: "Mật ong và siro",
            parent_id: 100650,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100820,
            name: "Jam & Spread",
            display_name: "Mứt",
            parent_id: 100650,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100821,
            name: "Cereal, Granola & Oats",
            display_name: "Ngũ cốc",
            parent_id: 100650,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100822,
            name: "Breakfast Bar",
            display_name: "Thanh dinh dưỡng",
            parent_id: 100650,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100823,
            name: "Others",
            display_name: "Khác",
            parent_id: 100650,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100651,
        name: "Beverages",
        display_name: "Đồ uống",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100824,
            name: "Coffee",
            display_name: "Cà phê",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100825,
            name: "Tea & Tea Bags",
            display_name: "Trà & trà túi lọc",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100826,
            name: "Chocolate Drinks",
            display_name: "Thức uống Sô cô la",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100827,
            name: "Energy & Isotonic Drinks",
            display_name: "Nước tăng lực",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100828,
            name: "Water",
            display_name: "Nước tinh khiết",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100829,
            name: "Juice & Juice Vinegar",
            display_name: "Nước trái cây lên men",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100830,
            name: "Cordial & Syrups",
            display_name: "Siro pha",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100831,
            name: "Carbonated Drinks & Tonics",
            display_name: "Nước có ga",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100832,
            name: "Powdered Drink Mixes",
            display_name: "Bột pha",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100833,
            name: "Dessert Drink",
            display_name: "Đồ tráng miệng",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100834,
            name: "Traditional & Herbal Drinks",
            display_name: "Trà thảo mộc",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100835,
            name: "Drink Toppings",
            display_name: "Topping",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100836,
            name: "Non-dairy Milk",
            display_name: "Sữa thực vật",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100837,
            name: "Others",
            display_name: "Khác",
            parent_id: 100651,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100652,
        name: "Dairy & Eggs",
        display_name: "Sữa - trứng",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100838,
            name: "Milk",
            display_name: "Sữa",
            parent_id: 100652,
            has_active_children: true,
            has_children: true,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100839,
            name: "Yogurt & Cultured Milk",
            display_name: "Sữa chua",
            parent_id: 100652,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100840,
            name: "Creamers",
            display_name: "Bột kem béo",
            parent_id: 100652,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100841,
            name: "Butter & Margarine",
            display_name: "Bơ động vật & thực vật",
            parent_id: 100652,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100842,
            name: "Cheese & Cheese Powder",
            display_name: "Phô mai & bột phô mai",
            parent_id: 100652,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100843,
            name: "Ice cream",
            display_name: "Kem",
            parent_id: 100652,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100844,
            name: "Eggs",
            display_name: "Trứng",
            parent_id: 100652,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100845,
            name: "Beancurd",
            display_name: "Đậu phụ",
            parent_id: 100652,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100846,
            name: "Others",
            display_name: "Khác",
            parent_id: 100652,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100653,
        name: "Fresh & Frozen Food",
        display_name: "Thực phẩm tươi sống & đông lạnh",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100847,
            name: "Meat",
            display_name: "Thịt",
            parent_id: 100653,
            has_active_children: true,
            has_children: true,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100848,
            name: "Seafood",
            display_name: "Hải sản",
            parent_id: 100653,
            has_active_children: true,
            has_children: true,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100849,
            name: "Vegetarian Meat",
            display_name: "Thịt chay",
            parent_id: 100653,
            has_active_children: false,
            has_children: false,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
          {
            id: 100850,
            name: "Others",
            display_name: "Khác",
            parent_id: 100653,
            has_active_children: false,
            has_children: false,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
          {
            id: 100851,
            name: "Vegetables",
            display_name: "Rau củ",
            parent_id: 100653,
            has_active_children: true,
            has_children: true,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
          {
            id: 100852,
            name: "Fruits",
            display_name: "Trái cây",
            parent_id: 100653,
            has_active_children: true,
            has_children: true,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
          {
            id: 100853,
            name: "Mushroom",
            display_name: "Nấm",
            parent_id: 100653,
            has_active_children: false,
            has_children: false,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
          {
            id: 100854,
            name: "Frozen Processed Food",
            display_name: "Thực phẩm đông lạnh chế biến sẵn",
            parent_id: 100653,
            has_active_children: false,
            has_children: false,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
          {
            id: 100855,
            name: "Processed Meat & Seafood",
            display_name: "Thịt và hải sản chế biến sẵn",
            parent_id: 100653,
            has_active_children: false,
            has_children: false,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100654,
        name: "Bakery",
        display_name: "Các loại bánh",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100856,
            name: "Breads",
            display_name: "Bánh mì",
            parent_id: 100654,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100857,
            name: "Cakes & Pies",
            display_name: "Bánh kem",
            parent_id: 100654,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100858,
            name: "Pastry",
            display_name: "Bánh ngọt/ pastry",
            parent_id: 100654,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100859,
            name: "Others",
            display_name: "Khác",
            parent_id: 100654,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100655,
        name: "Alcoholic Beverages",
        display_name: "Đồ uống có cồn",
        parent_id: 100629,
        has_active_children: true,
        has_children: true,
        children: [
          {
            id: 100860,
            name: "Beer & Cider",
            display_name: "Bia và trái cây lên men",
            parent_id: 100655,
            has_active_children: false,
            has_children: false,
            children: [],

            is_prohibit: false,
          },
          {
            id: 100861,
            name: "Wine & Champagne",
            display_name: "Rượu vang & Sâm panh",
            parent_id: 100655,
            has_active_children: false,
            has_children: false,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
          {
            id: 100862,
            name: "Liquor & Spirits",
            display_name: "Rượu mạnh",
            parent_id: 100655,
            has_active_children: false,
            has_children: false,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
          {
            id: 100863,
            name: "Sake, Soju & Umeshu",
            display_name: "Rượu sake, soju & umeshu",
            parent_id: 100655,
            has_active_children: false,
            has_children: false,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
          {
            id: 100864,
            name: "Others",
            display_name: "Khác",
            parent_id: 100655,
            has_active_children: false,
            has_children: false,
            children: [],
            region_setting: {
              enable_size_chart: false,
              low_stock_value: 0,
              dimension_mandatory: false,
              is_fashion_category: false,
              enable_compatibility: false,
              is_local_block: false,
              is_cb_block: true,
              gtin_validation_rule: 0,
            },
            is_prohibit: false,
          },
        ],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100656,
        name: "Gift Set & Hampers",
        display_name: "Bộ quà tặng",
        parent_id: 100629,
        has_active_children: false,
        has_children: false,
        children: [],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
      {
        id: 100657,
        name: "Others",
        display_name: "Khác",
        parent_id: 100629,
        has_active_children: false,
        has_children: false,
        children: [],
        region_setting: {
          enable_size_chart: false,
          low_stock_value: 0,
          dimension_mandatory: false,
          is_fashion_category: false,
          enable_compatibility: false,
          is_local_block: false,
          is_cb_block: false,
          gtin_validation_rule: 0,
        },
        is_prohibit: false,
      },
    ],
  },
];
