services:
  frontend:
    image: lhoangcuong1996/original_food_client:latest
    ports:
      - "3000:3000"
    networks:
      - docker-network

  backend:
    image: lhoangcuong1996/original_food_server:latest
    ports:
      - "4000:4000"
    networks:
      - docker-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: always
    networks:
      - docker-network
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" # Auto renew certificate
    command: certbot --nginx -d original-food.shop -d api.original-food.shop # Get certificate
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge
