name: Deploy to VPS

on:
  push:
    branches:
      - master  # hoặc tên nhánh bạn muốn trigger việc deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'  # hoặc phiên bản Node.js bạn đang sử dụng
    - name: Install pnpm  # nếu dự án xài pnpm thì phải install ở đây
        run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm ci
    - name: Build
      run: npm run build
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /cuong/organic-food/client
          git pull origin main
          npm ci
          npm run build
          pm2 restart orgnanic-food
