name: Deploy client to VPS

on:
  push:
    branches:
      - master  # hoặc tên nhánh bạn muốn trigger việc deploy
    paths:
      - 'client/**'  # Chỉ trigger khi có thay đổi trong thư mục client
      - ".github/workflows/client-deploy.yml"  # Trigger khi có thay đổi trong file workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: client
        file: client/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/organic-food:latest
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker stop organic-food-client
          docker rm organic-food-client
          docker pull ${{ secrets.DOCKER_USERNAME }}/organic-food:latest
          docker run -d -p 3000:3000 --name organic-food-client ${{ secrets.DOCKER_USERNAME }}/organic-food:latest