name: Deploy client to VPS

on:
  push:
    branches:
      - master  # hoặc tên nhánh bạn muốn trigger việc deploy
    paths:
      - 'client/**'  # Chỉ trigger khi có thay đổi trong thư mục client
      - ".github/workflows/client-deploy.yml"  # Trigger khi có thay đổi trong file workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'  # hoặc phiên bản Node.js bạn đang sử dụng
    - name: Install pnpm  # nếu dự án xài pnpm thì phải install ở đây
      uses: pnpm/action-setup@v2
      with:
        version: 8 
    - name: Install dependencies
      working-directory: ./client # vì src client nằm trong client nên phải chuyển đến thư mục client
      run: pnpm install
    # Nếu sử dụng npm thì sử dụng lệnh sau
    #- name: Install dependencies
    #  run: npm ci
    - name: Build
      working-directory: ./client
      run: npm run build
    - name: Copy files to VPS
      run: |
        scp -r ./client/.next ${{ secrets.USER }}/${{ secrets.HOST }}:/home/projects/organic-food/client
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_IP: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/projects/organic-food/client
          npm run start
