#
name: Deploy server to VPS

on:
  push:
    branches:
      - master  # hoặc tên nhánh bạn muốn trigger việc deploy
    paths:
      - 'server/**'  # Chỉ trigger khi có thay đổi trong thư mục server
      - ".github/workflows/server-deploy.yml"  # Trigger khi có thay đổi trong file workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> server/.env
        echo PORT=${{ vars.SERVER_PORT }} >> server/.env
        echo DOMAIN=${{ vars.SERVER_DOMAIN }} >> server/.env
        echo PROTOCOL=${{ vars.SERVER_PROTOCOL }} >> server/.env
        echo TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} >> server/.env
        echo ACCESS_TOKEN_EXPIRES_IN=${{ vars.ACCESS_TOKEN_EXPIRES_IN }} >> server/.env
        echo REFRESH_TOKEN_EXPIRES_IN=${{ vars.REFRESH_TOKEN_EXPIRES_IN }} >> server/.env
        echo COOKIE_MODE=false >> server/.env
        echo UPLOAD_FOLDER=${{ vars.UPLOAD_FOLDER }} >> server/.env
        echo IS_PRODUCTION=true >> server/.env
        echo PRODUCTION_URL=${{ vars.PRODUCTION_URL }} >> server/.env

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: server
        file: server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_NAMESPACE }}/organic_food_server:latest # Namespace: lhoangcuong1996
    
    - name: SSH into VPS and deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "config/docker-compose.yml,config/nginx.conf"
        target: "/home/projects/organic-food/"
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/projects/organic-food/config
          docker-compose down
          docker-compose pull & docker-compose up
